version: "3"

services:
  # Grafana
  grafana:
    container_name: grafana
    restart: 'unless-stopped'
    image: grafana/grafana
    user: '0' # don't do this pls
    volumes:
      - ./provisioning/:/etc/grafana/provisioning/
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=admin
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=cadvisor
      - INFLUXDB_USER=root
      - GF_AUTH_ANONYMOUS_ENABLED=true

  # InfluxDB
  influxdb:
    container_name: influxdb
    restart: 'unless-stopped'
    image: tutum/influxdb
    ports:
      - 8086:8086
      - 8083:8083
    expose:
      - 8090
      - 8099
    environment:
      - PRE_CREATE_DB=cadvisor
    volumes:
      - influxData

  # CAdvisor
  cadvisor:
    container_name: cadvisor
    restart: 'unless-stopped'
    image: google/cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=95.216.209.237:8086

  # Prometheus
  prometheus:
    container_name: prometheus
    restart: 'unless-stopped'
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml